---
- hosts: webservers 
  gather_facts: yes
- hosts: HAproxy
  gather_facts: yes
  become: yes
  become_method: sudo
  
  tasks:
  - name: "system update and package upgrade"
    apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 7200
        force_apt_get: true
        
  - name: "installing HAproxy"
    apt:
        name: haproxy
        state: latest
        force_apt_get: yes
        
  - name: "Configuring HAproxy"  
    template:
         src: "./haproxy.j2"
         dest: "/etc/haproxy/haproxy.cfg"
    notify: "Start HAproxy"
  
  - name: "restarting HAproxy"
    service:
         name: haproxy
         state: started
         enabled: yes
  
  handlers:
  - name: "Start HAproxy"
    service:
         name: haproxy
         state: restarted
              
- hosts: webservers
  gather_facts: yes
  tasks:
  - name: "system update and package upgrade on webservers"
    become: yes
    become_method: sudo
    apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 7200
        force_apt_get: true
  - name: "installing pip3"
    pip:
        name: pip
        extra_args: --upgrade
        executable: pip3
        
  - name: "copying Application2.py"
    copy:
        src: application2.py
        dest: /home/ubuntu/application2.py
        owner: ubuntu
        mode: '0644'
  - name: "Running Flask app"
    shell: |
        export FLASK_APP=./application2.py
        export FLASK_RUN_HOST=0.0.0.0
        export FLASK_RUN_PORT=8080
        flask run
        
   





